import { defaultBaseConfig, mergeConfigs } from '@chakra-ui/react'

export const config = mergeConfigs(defaultBaseConfig, {
  globalCss: {
    html: {
      colorPalette: 'default',
      bg: '{colors.shell.bg}',
    },
  },
  theme: {
    breakpoints: {
      sm: '20rem',
      md: '48rem',
      lg: '60rem',
      xl: '75rem',
      '2xl': '96rem',
      '3xl': '120rem',
    },
    tokens: {
      colors: {
        /**
         * Black and white shades
         */
        white: {
          DEFAULT: { value: 'rgba(255, 255, 255, 1)' },
          '50': { value: 'rgba(255, 255, 255, 0.04)' },
          '100': { value: 'rgba(255, 255, 255, 0.06)' },
          '200': { value: 'rgba(255, 255, 255, 0.08)' },
          '300': { value: 'rgba(255, 255, 255, 0.16)' },
          '400': { value: 'rgba(255, 255, 255, 0.24)' },
          '500': { value: 'rgba(255, 255, 255, 0.36)' },
          '600': { value: 'rgba(255, 255, 255, 0.48)' },
          '700': { value: 'rgba(255, 255, 255, 0.64)' },
          '800': { value: 'rgba(255, 255, 255, 0.80)' },
          '900': { value: 'rgba(255, 255, 255, 0.92)' },
          '950': { value: 'rgba(255, 255, 255, 0.95)' },
        },
        black: {
          DEFAULT: { value: 'rgba(1, 1, 1, 1)' },
          '50': { value: 'rgba(1, 1, 1, 0.04)' },
          '100': { value: 'rgba(1, 1, 1, 0.06)' },
          '200': { value: 'rgba(1, 1, 1, 0.08)' },
          '300': { value: 'rgba(1, 1, 1, 0.16)' },
          '400': { value: 'rgba(1, 1, 1, 0.24)' },
          '500': { value: 'rgba(1, 1, 1, 0.36)' },
          '600': { value: 'rgba(1, 1, 1, 0.48)' },
          '700': { value: 'rgba(1, 1, 1, 0.64)' },
          '800': { value: 'rgba(1, 1, 1, 0.80)' },
          '900': { value: 'rgba(1, 1, 1, 0.92)' },
          '950': { value: 'rgba(1, 1, 1, 0.96)' },
        },
        gray: {
          50: { value: '#F9FAFB' },
          100: { value: '#F3F4F6' },
          200: { value: '#E5E7EB' },
          300: { value: '#D1D5DB' },
          400: { value: '#9CA3AF' },
          500: { value: '#6B7280' },
          600: { value: '#4B5563' },
          700: { value: '#374151' },
          800: { value: '#1F2937' },
          900: { value: '#111827' },
          950: { value: '#030712' },
        },
        red: {
          50: { value: '#FEF2F2' },
          100: { value: '#FEE2E2' },
          200: { value: '#FECACA' },
          300: { value: '#FCA5A5' },
          400: { value: '#F87171' },
          500: { value: '#EF4444' },
          600: { value: '#DC2626' },
          700: { value: '#B91C1C' },
          800: { value: '#991B1B' },
          900: { value: '#7F1D1D' },
          950: { value: '#450A0A' },
        },
        pink: {
          50: { value: '#FDF2F8' },
          100: { value: '#FCE7F3' },
          200: { value: '#FBCFE8' },
          300: { value: '#F9A8D4' },
          400: { value: '#F472B6' },
          500: { value: '#EC4899' },
          600: { value: '#DB2777' },
          700: { value: '#BE185D' },
          800: { value: '#9D174D' },
          900: { value: '#831843' },
          950: { value: '#500724' },
        },
        purple: {
          50: { value: '#F5F3FF' },
          100: { value: '#EDE9FE' },
          200: { value: '#DDD6FE' },
          300: { value: '#C4B5FD' },
          400: { value: '#A78BFA' },
          500: { value: '#8B5CF6' },
          600: { value: '#7C3AED' },
          700: { value: '#6D28D9' },
          800: { value: '#5B21B6' },
          900: { value: '#4C1D95' },
          950: { value: '#2E1065' },
        },
        cyan: {
          50: { value: '#ECFEFF' },
          100: { value: '#CFFAFE' },
          200: { value: '#A5F3FC' },
          300: { value: '#67E8F9' },
          400: { value: '#22D3EE' },
          500: { value: '#06B6D4' },
          600: { value: '#0891B2' },
          700: { value: '#0E7490' },
          800: { value: '#155E75' },
          900: { value: '#164E63' },
          950: { value: '#083344' },
        },
        blue: {
          50: { value: '#EFF6FF' },
          100: { value: '#DBEAFE' },
          200: { value: '#BFDBFE' },
          300: { value: '#93C5FD' },
          400: { value: '#60A5FA' },
          500: { value: '#3B82F6' },
          600: { value: '#2563EB' },
          700: { value: '#1D4ED8' },
          800: { value: '#1E40AF' },
          900: { value: '#1E3A8A' },
          950: { value: '#172554' },
        },
        teal: {
          50: { value: '#F0FDFA' },
          100: { value: '#CCFBF1' },
          200: { value: '#99F6E4' },
          300: { value: '#5EEAD4' },
          400: { value: '#2DD4BF' },
          500: { value: '#14B8A6' },
          600: { value: '#0D9488' },
          700: { value: '#0F766E' },
          800: { value: '#115E59' },
          900: { value: '#134E4A' },
          950: { value: '#042F2E' },
        },
        green: {
          50: { value: '#F0FDF4' },
          100: { value: '#DCFCE7' },
          200: { value: '#BBF7D0' },
          300: { value: '#86EFAC' },
          400: { value: '#4ADE80' },
          500: { value: '#22C55E' },
          600: { value: '#16A34A' },
          700: { value: '#15803D' },
          800: { value: '#166534' },
          900: { value: '#14532D' },
          950: { value: '#052E16' },
        },
        yellow: {
          50: { value: '#FEFCE8' },
          100: { value: '#FEF9C3' },
          200: { value: '#FEF08A' },
          300: { value: '#FDE047' },
          400: { value: '#FACC15' },
          500: { value: '#EAB308' },
          600: { value: '#CA8A04' },
          700: { value: '#A16207' },
          800: { value: '#854D0E' },
          900: { value: '#713F12' },
          950: { value: '#422006' },
        },
        orange: {
          50: { value: '#FFF7ED' },
          100: { value: '#FFEDD5' },
          200: { value: '#FED7AA' },
          300: { value: '#FDBA74' },
          400: { value: '#FB923C' },
          500: { value: '#F97316' },
          600: { value: '#EA580C' },
          700: { value: '#C2410C' },
          800: { value: '#9A3412' },
          900: { value: '#7C2D12' },
          950: { value: '#431407' },
        },
        categorical: {
          1: { value: '#23B5A5' },
          2: { value: '#3D4EB6' },
          3: { value: '#FF7E25' },
          4: { value: '#DC3E8C' },
          5: { value: '#6D88FF' },
          6: { value: '#81DE61' },
          7: { value: '#007DE6' },
          8: { value: '#5E33DB' },
          9: { value: '#E8C464' },
          10: { value: '#D15714' },
          11: { value: '#3CA76F' },
          12: { value: '#6C5000' },
        },
      },
      fonts: {
        heading: {
          value: "'Raleway', 'Roboto', 'Segoe UI', 'sans-serif'",
        },
        body: {
          value:
            "'Roboto', 'Segoe UI', 'Helvetica Neue', 'Noto Sans', 'Liberation Sans', 'Arial', 'sans-serif', 'system-ui', '-apple-system'",
        },
        monospace: {
          value:
            "'IntelOne Mono', 'SFMono-Regular', 'Menlo', 'Monaco', 'Consolas', 'Liberation Mono', 'Courier New', 'monospace'",
        },
      },
    },
    semanticTokens: {
      colors: {
        primary: {
          bg: { value: { base: '{colors.yellow.400}', _dark: '{colors.yellow.400}' } },
          bg_hover: { value: { base: '{colors.yellow.500}', _dark: '{colors.yellow.500}' } },
          border: { value: { base: '{colors.yellow.500}', _dark: '{colors.yellow.500}' } },
          fg: { value: { base: '{colors.black}', _dark: '{colors.black}' } },
        },
        secondary: {
          bg: { value: { base: '{colors.blue.500}', _dark: '{colors.blue.400}' } },
          bg_hover: { value: { base: '{colors.blue.600}', _dark: '{colors.blue.500}' } },
          border: { value: { base: '{colors.blue.600}', _dark: '{colors.blue.500}' } },
          fg: { value: { base: 'white', _dark: '{colors.blue.950}' } },
        },
        success: {
          bg: { value: { base: '{colors.green.500}', _dark: '{colors.green.400}' } },
          bg_hover: { value: { base: '{colors.green.600}', _dark: '{colors.green.500}' } },
          border: { value: { base: '{colors.green.600}', _dark: '{colors.green.500}' } },
          fg: { value: { base: 'white', _dark: '{colors.green.950}' } },
        },
        info: {
          fg: { value: { base: '{colors.blue.600}', _dark: '{colors.blue.400}' } },
          bg: { value: { base: '{colors.blue.200}', _dark: '{colors.blue.950}' } },
          bg_hover: { value: { base: '{colors.blue.300}', _dark: '{colors.blue.800}' } },
          text: { value: { base: '{colors.blue.600}', _dark: '{colors.blue.300}' } },
          border: { value: { base: '{colors.blue.300}', _dark: '{colors.blue.400}' } },
        },
        warning: {
          bg: { value: { base: '{colors.orange.500}', _dark: '{colors.orange.400}' } },
          bg_hover: { value: { base: '{colors.orange.600}', _dark: '{colors.orange.500}' } },
          border: { value: { base: '{colors.orange.600}', _dark: '{colors.orange.500}' } },
          fg: { value: { base: 'white', _dark: '{colors.orange.950}' } },
        },
        error: {
          bg: { value: { base: '{colors.red.500}', _dark: '{colors.red.400}' } },
          bg_hover: { value: { base: '{colors.red.600}', _dark: '{colors.red.500}' } },
          border: { value: { base: '{colors.red.600}', _dark: '{colors.red.500}' } },
          fg: { value: { base: 'white', _dark: '{colors.red.950}' } },
        },
        highlight: {
          bg: { value: { base: '{colors.purple.500}', _dark: '{colors.purple.400}' } },
          bg_hover: { value: { base: '{colors.purple.600}', _dark: '{colors.purple.500}' } },
          border: { value: { base: '{colors.purple.600}', _dark: '{colors.purple.500}' } },
          fg: { value: { base: 'white', _dark: '{colors.purple.950}' } },
        },
      },
    },
    recipes: {
      button: {
        base: {
          borderWidth: '2px',
          transition: 'all 0.2s ease-in-out',
          _active: {
            transform: 'scale(0.98)',
          },
          // General disabled styles - apply opacity and cursor, but not color
          _disabled: {
            opacity: 0.6,
            cursor: 'not-allowed',
          },
        },
        variants: {
          color: {
            primary: {
              '--button-fg': 'colors.primary.fg',
              '--button-bg': 'colors.primary.bg',
              '--button-border': 'colors.primary.border',
              '--button-hover-bg': 'colors.primary.bg_hover',
            },
            secondary: {
              '--button-fg': 'colors.secondary.fg',
              '--button-bg': 'colors.secondary.bg',
              '--button-border': 'colors.secondary.border',
              '--button-hover-bg': 'colors.secondary.bg_hover',
            },
            success: {
              '--button-fg': 'colors.success.fg',
              '--button-bg': 'colors.success.bg',
              '--button-border': 'colors.success.border',
              '--button-hover-bg': 'colors.success.bg_hover',
            },
            info: {
              '--button-fg': 'colors.info.fg',
              '--button-bg': 'colors.info.bg',
              '--button-border': 'colors.info.border',
              '--button-hover-bg': 'colors.info.bg_hover',
            },
            warning: {
              '--button-fg': 'colors.warning.fg',
              '--button-bg': 'colors.warning.bg',
              '--button-border': 'colors.warning.border',
              '--button-hover-bg': 'colors.warning.bg_hover',
            },
            error: {
              '--button-fg': 'colors.error.fg',
              '--button-bg': 'colors.error.bg',
              '--button-border': 'colors.error.border',
              '--button-hover-bg': 'colors.error.bg_hover',
            },
            highlight: {
              '--button-fg': 'colors.highlight.fg',
              '--button-bg': 'colors.highlight.bg',
              '--button-border': 'colors.highlight.border',
              '--button-hover-bg': 'colors.highlight.bg_hover',
            },
          },
          variant: {
            solid: {
              bg: 'var(--button-bg)',
              color: 'var(--button-fg)',
              borderColor: 'var(--button-border)',
              _hover: {
                bg: 'var(--button-hover-bg)',
                _disabled: {
                  bg: 'var(--button-bg)',
                },
              },
              _disabled: {
                bg: 'var(--button-bg)',
                borderColor: 'var(--button-border)',
              },
              _loading: {
                bg: 'var(--button-bg)',
                borderColor: 'var(--button-border)',
              },
            },
            outline: {
              bg: 'transparent',
              borderColor: 'var(--button-bg)',
              color: 'var(--button-bg)',
              _hover: {
                bg: 'var(--button-bg)',
                color: 'var(--button-fg)',
                _disabled: {
                  bg: 'transparent',
                },
              },
              _disabled: {
                borderColor: 'var(--button-bg)',
                color: 'var(--button-bg)',
                bg: 'transparent',
              },
              _loading: {
                borderColor: 'var(--button-bg)',
                color: 'var(--button-bg)',
              },
            },
            ghost: {
              bg: 'transparent',
              borderColor: 'transparent',
              color: 'var(--button-bg)',
              _hover: {
                bg: 'var(--button-bg)',
                color: 'var(--button-fg)',
                _disabled: {
                  bg: 'transparent',
                },
              },
              _disabled: {
                color: 'var(--button-bg)',
                bg: 'transparent',
                borderColor: 'transparent',
              },
              _loading: {
                color: 'var(--button-bg)',
                borderColor: 'transparent',
              },
            },
            link: {
              bg: 'transparent',
              color: 'var(--button-bg)',
              borderColor: 'transparent',
              _hover: {
                textDecoration: 'underline',
              },
            },
          },
        },
      },
    },
  },
})
