name: "Setup Nodejs environment"
description: "Setup Nodejs environment including all dependencies to execute runtime jobs"
inputs:
  run_install:
    description: Run the install pnpm command
    default: "false"

runs:
  using: "composite"
  steps:
    - name: 📣 Enable Corepack
      run: corepack enable
      shell: bash

    - uses: pnpm/action-setup@v4
      name: Install pnpm
      id: pnpm-install
      with:
        version: 10
        run_install: ${{ inputs.run_install }}

    - uses: actions/setup-node@v4
      with:
        node-version: 22
        registry-url: https://npm.pkg.github.com
        scope: '@hivemq'
        cache: 'pnpm'

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
      env:
        PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
