name: "Setup Nodejs environment"
description: "Setup Nodejs environment including all dependencies to execute runtime jobs"
inputs:
  run_install:
    description: Run the install pnpm command
    default: "false"

runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@v2
      name: Install pnpm
      id: pnpm-install
      with:
        version: 8.15.4
        run_install: false

    - uses: actions/setup-node@v3
      with:
        node-version: 20.11.1
        registry-url: https://npm.pkg.github.com
        scope: '@hivemq'

    - name: Store pnpm cache path
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - uses: actions/cache@v3
      name: Setup pnpm cache
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
