# Define automatic pull request label strategy based on branch-name patterns.
# 🪛 https://github.com/srvaroa/labeler

version: 1
labels:
  - label: "bug"
    branch: '^fix/'
  - label: "documentation"
    branch: '^documentation/'
  - label: "test"
    branch: '^test/'
  - label: "chore"
    branch: '^chore/'
  - label: "enhancement"
    branch: '^feature/'
  - label: "refactor"
    branch: '^refactor/'
  - label: "ci"
    branch: '^ci/'
