export const semanticTokens = {
  /**
   * HiveMQ related custom semantic Tokens
   */
  primary: {
    bg: {value: {base: '{colors.yellow.400}', _dark: '{colors.yellow.400}'}},
    bg_hover: {value: {base: '{colors.yellow.500}', _dark: '{colors.yellow.500}'}},
    fg: {value: {base: '{colors.black}', _dark: '{colors.black}'}},
    border: {value: {base: '{colors.yellow.500}', _dark: '{colors.yellow.500}'}},
  },
  secondary: {
    bg: {value: {base: '{colors.blue.500}', _dark: '{colors.blue.400}'}},
    bg_hover: {value: {base: '{colors.blue.600}', _dark: '{colors.blue.500}'}},
    border: {value: {base: '{colors.blue.600}', _dark: '{colors.blue.500}'}},
    fg: {value: {base: 'white', _dark: '{colors.blue.950}'}},
  },
  success: {
    bg: {value: {base: '{colors.green.500}', _dark: '{colors.green.400}'}},
    bg_hover: {value: {base: '{colors.green.600}', _dark: '{colors.green.500}'}},
    border: {value: {base: '{colors.green.600}', _dark: '{colors.green.500}'}},
    fg: {value: {base: 'white', _dark: '{colors.green.950}'}},
  },
  info: {
    fg: {value: {base: '{colors.blue.600}', _dark: '{colors.blue.400}'}},
    bg: {value: {base: '{colors.blue.200}', _dark: '{colors.blue.950}'}},
    bg_hover: {value: {base: '{colors.blue.300}', _dark: '{colors.blue.800}'}},
    text: {value: {base: '{colors.blue.600}', _dark: '{colors.blue.300}'}},
    border: {value: {base: '{colors.blue.300}', _dark: '{colors.blue.400}'}},
  },
  warning: {
    bg: {value: {base: '{colors.orange.500}', _dark: '{colors.orange.400}'}},
    bg_hover: {value: {base: '{colors.orange.600}', _dark: '{colors.orange.500}'}},
    border: {value: {base: '{colors.orange.600}', _dark: '{colors.orange.500}'}},
    fg: {value: {base: 'white', _dark: '{colors.orange.950}'}},
  },
  error: {
    bg: {value: {base: '{colors.red.500}', _dark: '{colors.red.400}'}},
    bg_hover: {value: {base: '{colors.red.600}', _dark: '{colors.red.500}'}},
    border: {value: {base: '{colors.red.600}', _dark: '{colors.red.500}'}},
    fg: {value: {base: 'white', _dark: '{colors.red.950}'}},
  },
  highlight: {
    bg: {value: {base: '{colors.purple.500}', _dark: '{colors.purple.400}'}},
    bg_hover: {value: {base: '{colors.purple.600}', _dark: '{colors.purple.500}'}},
    border: {value: {base: '{colors.purple.600}', _dark: '{colors.purple.500}'}},
    fg: {value: {base: 'white', _dark: '{colors.purple.950}'}},
  },
  /**
   * Color mirror semantic tokens
   * TODO: @RobinAtherton - Don't these miss some of the things that we have in our custom semantic tokens and vice versa
   */
  gray: {
    contrast: {value: {base: '{colors.white}', _dark: '{colors.black}'}},
    fg: {value: {base: '{colors.gray.800}', _dark: '{colors.gray.200}'}},
    subtle: {value: {base: '{colors.gray.100}', _dark: '{colors.gray.900}'}},
    muted: {value: {base: '{colors.gray.200}', _dark: '{colors.gray.800}'}},
    emphasized: {value: {base: '{colors.gray.300}', _dark: '{colors.gray.700}'}},
    solid: {value: {base: '{colors.gray.900}', _dark: '{colors.white}'}},
    focusRing: {value: {base: '{colors.gray.400}', _dark: '{colors.gray.400}'}},
  },
  red: {
    contrast: {value: {base: '{colors.white}', _dark: '{colors.white}'}},
    fg: {value: {base: '{colors.red.700}', _dark: '{colors.red.300}'}},
    subtle: {value: {base: '{colors.red.100}', _dark: '{colors.red.900}'}},
    muted: {value: {base: '{colors.red.200}', _dark: '{colors.red.800}'}},
    emphasized: {value: {base: '{colors.red.300}', _dark: '{colors.red.700}'}},
    solid: {value: {base: '{colors.red.600}', _dark: '{colors.red.600}'}},
    focusRing: {value: {base: '{colors.red.400}', _dark: '{colors.red.400}'}},
  },
  pink: {
    contrast: {value: {base: '{colors.white}', _dark: '{colors.white}'}},
    fg: {value: {base: '{colors.pink.700}', _dark: '{colors.pink.300}'}},
    subtle: {value: {base: '{colors.pink.100}', _dark: '{colors.pink.900}'}},
    muted: {value: {base: '{colors.pink.200}', _dark: '{colors.pink.800}'}},
    emphasized: {value: {base: '{colors.pink.300}', _dark: '{colors.pink.700}'}},
    solid: {value: {base: '{colors.pink.600}', _dark: '{colors.pink.600}'}},
    focusRing: {value: {base: '{colors.pink.400}', _dark: '{colors.pink.400}'}},
  },
  purple: {
    contrast: {value: {base: '{colors.white}', _dark: '{colors.white}'}},
    fg: {value: {base: '{colors.purple.700}', _dark: '{colors.purple.300}'}},
    subtle: {value: {base: '{colors.purple.100}', _dark: '{colors.purple.900}'}},
    muted: {value: {base: '{colors.purple.200}', _dark: '{colors.purple.800}'}},
    emphasized: {value: {base: '{colors.purple.300}', _dark: '{colors.purple.700}'}},
    solid: {value: {base: '{colors.purple.600}', _dark: '{colors.purple.600}'}},
    focusRing: {value: {base: '{colors.purple.400}', _dark: '{colors.purple.400}'}},
  },
  cyan: {
    contrast: {value: {base: '{colors.white}', _dark: '{colors.white}'}},
    fg: {value: {base: '{colors.cyan.700}', _dark: '{colors.cyan.300}'}},
    subtle: {value: {base: '{colors.cyan.100}', _dark: '{colors.cyan.900}'}},
    muted: {value: {base: '{colors.cyan.200}', _dark: '{colors.cyan.800}'}},
    emphasized: {value: {base: '{colors.cyan.300}', _dark: '{colors.cyan.700}'}},
    solid: {value: {base: '{colors.cyan.600}', _dark: '{colors.cyan.600}'}},
    focusRing: {value: {base: '{colors.cyan.400}', _dark: '{colors.cyan.400}'}},
  },
  blue: {
    contrast: {value: {base: '{colors.white}', _dark: '{colors.white}'}},
    fg: {value: {base: '{colors.blue.700}', _dark: '{colors.blue.300}'}},
    subtle: {value: {base: '{colors.blue.100}', _dark: '{colors.blue.900}'}},
    muted: {value: {base: '{colors.blue.200}', _dark: '{colors.blue.800}'}},
    emphasized: {value: {base: '{colors.blue.300}', _dark: '{colors.blue.700}'}},
    solid: {value: {base: '{colors.blue.600}', _dark: '{colors.blue.600}'}},
    focusRing: {value: {base: '{colors.blue.400}', _dark: '{colors.blue.400}'}},
  },
  teal: {
    contrast: {value: {base: '{colors.white}', _dark: '{colors.white}'}},
    fg: {value: {base: '{colors.teal.700}', _dark: '{colors.teal.300}'}},
    subtle: {value: {base: '{colors.teal.100}', _dark: '{colors.teal.900}'}},
    muted: {value: {base: '{colors.teal.200}', _dark: '{colors.teal.800}'}},
    emphasized: {value: {base: '{colors.teal.300}', _dark: '{colors.teal.700}'}},
    solid: {value: {base: '{colors.teal.600}', _dark: '{colors.teal.600}'}},
    focusRing: {value: {base: '{colors.teal.400}', _dark: '{colors.teal.400}'}},
  },
  green: {
    contrast: {value: {base: '{colors.white}', _dark: '{colors.white}'}},
    fg: {value: {base: '{colors.green.700}', _dark: '{colors.green.300}'}},
    subtle: {value: {base: '{colors.green.100}', _dark: '{colors.green.900}'}},
    muted: {value: {base: '{colors.green.200}', _dark: '{colors.green.800}'}},
    emphasized: {value: {base: '{colors.green.300}', _dark: '{colors.green.700}'}},
    solid: {value: {base: '{colors.green.600}', _dark: '{colors.green.600}'}},
    focusRing: {value: {base: '{colors.green.400}', _dark: '{colors.green.400}'}},
  },
  yellow: {
    contrast: {value: {base: '{colors.black}', _dark: '{colors.black}'}},
    fg: {value: {base: '{colors.yellow.800}', _dark: '{colors.yellow.300}'}},
    subtle: {value: {base: '{colors.yellow.100}', _dark: '{colors.yellow.900}'}},
    muted: {value: {base: '{colors.yellow.200}', _dark: '{colors.yellow.800}'}},
    emphasized: {value: {base: '{colors.yellow.500}', _dark: '{colors.yellow.500}'}},
    solid: {value: {base: '{colors.yellow.300}', _dark: '{colors.yellow.300}'}},
    focusRing: {value: {base: '{colors.yellow.400}', _dark: '{colors.yellow.400}'}},
  },
  orange: {
    contrast: {value: {base: '{colors.black}', _dark: '{colors.black}'}},
    fg: {value: {base: '{colors.orange.700}', _dark: '{colors.orange.300}'}},
    subtle: {value: {base: '{colors.orange.100}', _dark: '{colors.orange.900}'}},
    muted: {value: {base: '{colors.orange.200}', _dark: '{colors.orange.800}'}},
    emphasized: {value: {base: '{colors.orange.300}', _dark: '{colors.orange.700}'}},
    solid: {value: {base: '{colors.orange.600}', _dark: '{colors.orange.500}'}},
    focusRing: {value: {base: '{colors.orange.400}', _dark: '{colors.orange.400}'}},
  },
  /**
   * Global
   */
  bg: {
    DEFAULT: {value: {base: '{colors.white}', _dark: '{colors.black}'}},
    subtle: {value: {base: '{colors.gray.50}', _dark: '{colors.gray.950}'}},
    muted: {value: {base: '{colors.gray.100}', _dark: '{colors.gray.900}'}},
    emphasized: {value: {base: '{colors.gray.200}', _dark: '{colors.gray.800}'}},
    inverted: {value: {base: '{colors.black}', _dark: '{colors.white}'}},
    panel: {value: {base: '{colors.white}', _dark: '{colors.black.950}'}},
    error: {value: {base: '{colors.red.50}', _dark: '{colors.red.950}'}},
    warning: {value: {base: '{colors.orange.50}', _dark: '{colors.orange.950}'}},
    success: {value: {base: '{colors.green.50}', _dark: '{colors.green.950}'}},
    info: {value: {base: '{colors.blue.50}', _dark: '{colors.blue.950}'}},
    primary: {value: {base: '{colors.yellow.50}', _dark: '{colors.yellow.950}'}},
  },
  fg: {
    DEFAULT: {value: {base: '{colors.black}', _dark: '{colors.gray.50}'}},
    subtle: {value: {base: '{colors.gray.400}', _dark: '{colors.gray.500}'}},
    muted: {value: {base: '{colors.gray.600}', _dark: '{colors.gray.600}'}},
    inverted: {value: {base: '{colors.gray.50}', _dark: '{colors.black}'}},
    error: {value: {base: '{colors.red.600}', _dark: '{colors.red.500}'}},
    warning: {value: {base: '{colors.orange.500}', _dark: '{colors.orange.400}'}},
    success: {value: {base: '{colors.green.600}', _dark: '{colors.green.400}'}},
    info: {value: {base: '{colors.blue.600}', _dark: '{colors.blue.400}'}},
    primary: {value: {base: '{colors.yellow.300}', _dark: '{colors.yellow.300}'}},
  },
  border: {
    DEFAULT: {value: {base: '{colors.gray.200}', _dark: '{colors.gray.800}'}},
    subtle: {value: {base: '{colors.gray.50}', _dark: '{colors.gray.950}'}},
    muted: {value: {base: '{colors.gray.100}', _dark: '{colors.gray.900}'}},
    emphasized: {value: {base: '{colors.gray.300}', _dark: '{colors.gray.700}'}},
    inverted: {value: {base: '{colors.gray.800}', _dark: '{colors.gray.200}'}},
    error: {value: {base: '{colors.red.500}', _dark: '{colors.red.400}'}},
    warning: {value: {base: '{colors.orange.500}', _dark: '{colors.orange.400}'}},
    success: {value: {base: '{colors.green.500}', _dark: '{colors.green.400}'}},
    info: {value: {base: '{colors.blue.500}', _dark: '{colors.blue.400}'}},
  },
  text: {
    // TODO check with eric, dark mode variable for default should be white here instead
    DEFAULT: {value: {base: '{colors.black}', _dark: '{colors.white}'}},
    muted: {value: {base: '{colors.gray.600}', _dark: '{colors.gray.400}'}},
    subtle: {value: {base: '{colors.gray.400}', _dark: '{colors.gray.500}'}},
    inverted: {value: {base: '{colors.gray.50}', _dark: '{colors.black}'}},
    error: {value: {base: '{colors.red.600}', _dark: '{colors.red.500}'}},
    warning: {value: {base: '{colors.yellow.600}', _dark: '{colors.yellow.300}'}},
    success: {value: {base: '{colors.green.600}', _dark: '{colors.green.300}'}},
    info: {value: {base: '{colors.blue.600}', _dark: '{colors.blue.300}'}},
  },
};