# This is a basic workflow to help you get started with Actions

name: CI

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ['main']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  tests:
    uses: ./.github/workflows/_tests.yml
    secrets: inherit

  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: tests

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/setup

      - run: pnpm build:testing

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './testing/dist/'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
