# Action to label pull requests based on the pre commit config that can be found here:
# 🪛 https://github.com/hivemq/ui-theme/blob/main/.pre-commit-config.yaml
# ---
# This action is a prerequisite to allow us to use release-drafter
# https://github.com/release-drafter/release-drafter

name: 🛠️ Pull Request Management

on:
  pull_request:
    types: [opened]

permissions:
  contents: read

jobs:
  label_pull_request:
    name: 'Add labels'
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: srvaroa/labeler@bf262763a8a8e191f5847873aecc0f29df84f957 # v1.14.0
        with:
          config_path: .github/configs/pull-request-labeler-config.yml
          use_local_config: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
