name: Publish Theme to GitHub Packages

on:
  release:
    types: [published]

jobs:
  # tests:
  #   uses: ./.github/workflows/_tests.yml
  #   secrets: inherit

  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    # needs: ['tests']

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/setup

      - run: pnpm build

      - run: pnpm publish --no-git-checks
        working-directory: theme
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
